"use client"
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "../components/Navbar";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "User Authentication",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname=usePathname()

  const  nonavbarRoutes=['/login','/signup']
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
<div className="max-w-1xl mx-auto p-4">
        
        {!(nonavbarRoutes).includes(pathname) && <Navbar/>}        
        {/* <Navbar/> */}
        <div className="mt-8">
        {children}
</div>
</div>

      </body>
    </html>
  );
}
